name: Generate authors RDF for monthly release

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 10 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:      
  make-authors-rdf:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      #- name: Setup R
      #  uses: r-lib/actions/setup-r@v2

      #- name: Install packages
      #  run: |
      #    sudo apt-get install libcurl4-openssl-dev
      #    Rscript -e 'install.packages(c("tidyr","dplyr","magrittr","yaml","WikidataQueryServiceR"))'

      #- name: Run citedin_lookup.R
      #  run: |
      #    Rscript -e "source('_rmd/authors-rdf.R')"

      - name: Set SSH config
        run: |
          touch $HOME/.ssh/config
          echo "Host *.wmflabs *.wikimedia.cloud" >> $HOME/.ssh/config
          echo "User apico" >> $HOME/.ssh/config
          echo "ProxyJump bastion.wmcloud.org:22" >> $HOME/.ssh/config
          touch $HOME/.ssh/known_hosts
          echo "bastion.wmcloud.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/Nm3DMfPBR14MWKs0cnuJMKic1v7cYUGUp1SrjStvm" >> $HOME/.ssh/known_hosts

      - name: Add SSH key
        uses: appleboy/scp-action@master
        with:
          host: "data.wikipathways.eqiad1.wikimedia.cloud"
          key: ${{ secrets.WMCLOUD_SSH_KEY }}
          source: "wikipathways-*-rdf-authors.zip"
          target: "/var/www/data.wikipathways.org/current/rdf/"
        #uses: webfactory/ssh-agent@v0.7.0
        #with:
        #  ssh-private-key: ${{ secrets.WMCLOUD_SSH_KEY }}
        #  log-public-key: false # true for debug

      #- name: Upload to data.wikipathway.org
      #  run: |
      #    for z in wikipathways-*-rdf-authors.zip; do
      #      echo "uploading $z"
      #      scp -vvvv $z data.wikipathways.eqiad1.wikimedia.cloud:/var/www/data.wikipathways.org/current/rdf/
      #    done