name: Generate authors RDF for monthly release

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 10 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:      
  make-authors-rdf:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e 'install.packages(c("tidyr","dplyr","magrittr","yaml","WikidataQueryServiceR"))'

      - name: Run citedin_lookup.R
        run: |
          Rscript -e "source('_rmd/authors-rdf.R')"

      - name: Set SSH config
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          echo "Host *.wmflabs *.wikimedia.cloud" > ~/.ssh/config
          echo "User apico" >> ~/.ssh/config
          echo "ProxyJump apico@bastion.wmcloud.org:22" >> ~/.ssh/config
          touch ~/.ssh/known_hosts
          echo "bastion.wmcloud.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/Nm3DMfPBR14MWKs0cnuJMKic1v7cYUGUp1SrjStvm" > ~/.ssh/known_hosts
          echo "data.wikipathways.eqiad1.wikimedia.cloud ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOspnIRzrBB/yAPLI9IXV70Ojh5xuvAOj5nwz8cGptfK" >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add - <<< "${{ secrets.WMCLOUD_SSH_KEY }}"

      - name: Upload to data.wikipathway.org
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "uploading wikipathways-*-rdf-authors.zip"
          scp wikipathways-*-rdf-authors.zip apico@data.wikipathways.eqiad1.wikimedia.cloud:/var/www/data.wikipathways.org/current/rdf/